delays:
  launch: 3
  setup: 20
features:
  enable_gui: false
  use_random_playlist: false
logging:
  backup_count: 3
  file: logs/automation.log
  level: INFO
  max_size: 5242880
names:
- edge
- teams
- outlook
paths:
  edge: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
  outlook: C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE
  teams: C:\Users\af940\AppData\Local\Microsoft\Teams\Update.exe
window_positions:
  edge:
    position:
      height: 1407
      width: 2575
      x: -7
      y: -7
  outlook:
    position:
      height: 1008
      width: 683
      x: 4843
      y: 546
  teams:
    position:
      height: 1009
      width: 1023
      x: 3833
      y: 546
youtube:
  alternative_playlists:
  - https://www.youtube.com/watch?v=5qap5aO4i9A
  - https://www.youtube.com/watch?v=DWcJFNfaw9c
  playlist_url: https://www.youtube.com/watch?v=jfKfPfyJRdk
